name: Checks and Validation
on:
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3
        id: app-token
        with:
          client-id: ${{ secrets.COMMIT_BOT_CLIENT_ID }}
          private-key: ${{ secrets.COMMIT_BOT_PRIVATE_KEY }}
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
        with:
          components: clippy,rustfmt

      - name: Cache cargo and rust files
        id: rust_cache
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          cache-on-failure: true
          shared-key: "linter_cache"

      - name: Run linters
        uses: profiidev/rust-lint-action@790d64dd437b648791344cbb590636ae3a47c923 # v4
        with:
          rustfmt: true
          clippy: true
          auto_fix: true
          git_sign_commits: true
          github_token: ${{ steps.app-token.outputs.token }}
